apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: app
        image: yourdockerhubusername/student-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
