version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
